/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author vetegan
 */
public class Ajouter extends JFrame {

    private Client user;
    private int currentProjectID;
    /**
     * Creates new form Ajouter
     */
    public Ajouter(Client user, int currentProjectID) {
        this.user = user;
        this.currentProjectID = currentProjectID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        collaborateurs = new JLabel();
        nomColab = new JTextField();
        valider = new JButton();
        logo_image = new JLabel();


        this.setMaximumSize(new java.awt.Dimension(439, 323));
        this.setMinimumSize(new java.awt.Dimension(439, 323));

        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (dimension.getWidth() / 2 - 439/ 2),
                (int) (dimension.getHeight() / 2 - 323 / 2));

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getContentPane().setLayout(new java.awt.GridBagLayout());

        collaborateurs.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        collaborateurs.setText("COLLABORATEURS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 138, 0, 0);
        getContentPane().add(collaborateurs, gridBagConstraints);

        nomColab.setText("WRITE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 0);
        getContentPane().add(nomColab, gridBagConstraints);
        nomColab.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                //JTextField source = (JTextField)e.getComponent();
                nomColab.setText("");
                //nomColab.removeFocusListener(this);
            }
        });

        valider.setText("Valider");
        valider.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (!nomColab.equals("")) {
                    user.ajouterCollab(nomColab.getText(), currentProjectID);
                }
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 171, 0, 0);
        getContentPane().add(valider, gridBagConstraints);

        logo_image.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        logo_image.setIcon(new ImageIcon(this.getClass().getResource("triangle.png")));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 43, 27, 24);
        getContentPane().add(logo_image, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Ajouter().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel collaborateurs;
    private JLabel logo_image;
    private JTextField nomColab;
    private JButton valider;
    // End of variables declaration//GEN-END:variables
}
