/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vetegan
 */
public class FenetreApp extends javax.swing.JFrame {

    private Client user;

    /**
     * Creates new form FenetreApp2
     */
    public FenetreApp(Client user) {
        this.user = user;
        initComponents();
    }

    public static void main(String[] args){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenetreApp(null).setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        panelCalendar = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        panel_rigth = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo_image = new javax.swing.JLabel();
        spectrum = new javax.swing.JLabel();
        projet = new javax.swing.JLabel();
        ajouterColab = new javax.swing.JButton();
        panelCentral = new java.awt.Panel();
        mesageButton = new javax.swing.JTextField();
        projectName = new javax.swing.JLabel();
        send = new javax.swing.JLabel();
        attach = new javax.swing.JLabel();
        scrollMessages = new java.awt.ScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setMaximumSize(new java.awt.Dimension(100, 800));
        panel1.setMinimumSize(new java.awt.Dimension(100, 800));

        exitButton.setIcon(new ImageIcon("/Users/vetegan/Desktop/Clase online/Algo/download.jpeg")); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(exitButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(725, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(33, 33, 33))
        );

        panelCalendar.setBackground(new java.awt.Color(0, 124, 163));

        name.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        name.setText("Valentina ETEGAN");
        name.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nameInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        username.setText("@vetegan");
        username.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                usernameInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        javax.swing.GroupLayout panelCalendarLayout = new javax.swing.GroupLayout(panelCalendar);
        panelCalendar.setLayout(panelCalendarLayout);
        panelCalendarLayout.setHorizontalGroup(
            panelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addComponent(username))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelCalendarLayout.setVerticalGroup(
            panelCalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username)
                .addContainerGap(671, Short.MAX_VALUE))
        );

        panel_rigth.setBackground(new java.awt.Color(255, 255, 255));
        panel_rigth.setMinimumSize(new java.awt.Dimension(500, 400));

        logo_image.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        logo_image.setIcon(new ImageIcon("/Users/vetegan/Desktop/Clase online/Algo/triangle logo Spectrum.png")); // NOI18N

        spectrum.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        spectrum.setText("SPECTRUM");

        projet.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        projet.setText(" Projets");
        projet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetMouseClicked(evt);
            }
        });
        projet.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                projetPropertyChange(evt);
            }
        });

        ajouterColab.setText("Ajouter un colaborator");

        javax.swing.GroupLayout panel_rigthLayout = new javax.swing.GroupLayout(panel_rigth);
        panel_rigth.setLayout(panel_rigthLayout);
        panel_rigthLayout.setHorizontalGroup(
            panel_rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(jLabel3))
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(logo_image))
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(spectrum))
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ajouterColab, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(projet))
        );
        panel_rigthLayout.setVerticalGroup(
            panel_rigthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rigthLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo_image)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spectrum)
                .addGap(51, 51, 51)
                .addComponent(ajouterColab)
                .addGap(18, 18, 18)
                .addComponent(projet)
                .addContainerGap(552, Short.MAX_VALUE))
        );

        panelCentral.setPreferredSize(new java.awt.Dimension(690, 803));

        mesageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesageButtonActionPerformed(evt);
            }
        });

        projectName.setFont(new java.awt.Font("New Peninim MT", 3, 24)); // NOI18N
        projectName.setText("PROJECT");
        projectName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                projectNameInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        send.setIcon(new ImageIcon("/Users/vetegan/Desktop/Spectrum-develop/1498877-200.png")); // NOI18N
        send.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt);
            }
        });

        attach.setIcon(new ImageIcon("/Users/vetegan/Desktop/Spectrum-develop/download (1).jpeg")); // NOI18N
        attach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attachMouseClicked(evt);
            }
        });

        scrollMessages.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCentralLayout = new javax.swing.GroupLayout(panelCentral);
        panelCentral.setLayout(panelCentralLayout);
        panelCentralLayout.setHorizontalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollMessages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCentralLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(attach)
                .addGap(18, 18, 18)
                .addComponent(mesageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send)
                .addGap(20, 20, 20))
        );
        panelCentralLayout.setVerticalGroup(
            panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(panelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(send)
                    .addComponent(mesageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attach))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(panelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_rigth, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(panel_rigth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        //changer
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nameInputMethodTextChanged

        // Add the name of the client;
    }//GEN-LAST:event_nameInputMethodTextChanged

    private void usernameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_usernameInputMethodTextChanged

        // Change the username;
    }//GEN-LAST:event_usernameInputMethodTextChanged

    private void projetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_projetMouseClicked

    private void projetPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_projetPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_projetPropertyChange

    private void mesageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesageButtonActionPerformed

        // send the message in the panelMessages;
    }//GEN-LAST:event_mesageButtonActionPerformed

    private void projectNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_projectNameInputMethodTextChanged
        // TO DO add your handling code here:
    }//GEN-LAST:event_projectNameInputMethodTextChanged

    private void attachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_attachMouseClicked

    private void sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMouseClicked

    public void printMsg(String msg) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterColab;
    private javax.swing.JLabel attach;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo_image;
    private javax.swing.JTextField mesageButton;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelCalendar;
    private java.awt.Panel panelCentral;
    private javax.swing.JPanel panel_rigth;
    private javax.swing.JLabel projectName;
    private javax.swing.JLabel projet;
    private java.awt.ScrollPane scrollMessages;
    private javax.swing.JLabel send;
    private javax.swing.JLabel spectrum;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
