/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.*;

/**
 *
 * @author vetegan
 */
public class NewProjet extends javax.swing.JFrame {

    /**
     * Creates new form NewProjet
     */
    public NewProjet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        projets = new javax.swing.JLabel();
        nouveauProjet = new javax.swing.JButton();
        logo_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 284));
        setMaximumSize(new java.awt.Dimension(400, 284));
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation((int) (dimension.getWidth() / 2 - 400/ 2),
                (int) (dimension.getHeight() / 2 - 284 / 2));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        projets.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        projets.setIcon(new javax.swing.ImageIcon("/Users/vetegan/Desktop/img_176810.png")); // NOI18N
        projets.setText("Mes Projets");
        projets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetsMouseClicked(evt);
            }
        });
        projets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        projets.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                projetsPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 57, 0, 0);
        getContentPane().add(projets, gridBagConstraints);

        nouveauProjet.setText("Nouveau projet");
        nouveauProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveauProjetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.ipady = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 33, 91, 118);
        getContentPane().add(nouveauProjet, gridBagConstraints);

        logo_image.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        logo_image.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("triangle.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 33, 0, 0);
        getContentPane().add(logo_image, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_projetsMouseClicked

    private void projetsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_projetsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_projetsPropertyChange

    private void nouveauProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauProjetActionPerformed
       // new Create(user).setVisible(true);
    }//GEN-LAST:event_nouveauProjetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewProjet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logo_image;
    private javax.swing.JButton nouveauProjet;
    private javax.swing.JLabel projets;
    // End of variables declaration//GEN-END:variables
}
